from constants import *
# === Constants ===
TILE_WIDTH, TILE_HEIGHT = TILE_SIZE, TILE_SIZE
VIEW_WIDTH, VIEW_HEIGHT = MAP_WIDTH, MAP_HEIGHT
SIDEBAR_SPACE_WIDTH = 350
SIDEBAR_SPACE_HEIGHT = 200
SCREEN_WIDTH, SCREEN_HEIGHT = TILE_WIDTH * VIEW_WIDTH + SIDEBAR_SPACE_WIDTH, TILE_HEIGHT * VIEW_HEIGHT + SIDEBAR_SPACE_HEIGHT  # Extra space for sidebar
ascii_offset_x = TILE_WIDTH//3
ascii_offset_y = TILE_HEIGHT//4

class EditState(Enum):
    TILE = 0
    OBJECT = 1
    INPUT = 2
    
