from constants import *
# === Constants ===
TILE_WIDTH, TILE_HEIGHT = TILE_SIZE//3, TILE_SIZE//3
VIEW_WIDTH, VIEW_HEIGHT = MAP_WIDTH*3, MAP_HEIGHT*3 + 8
SIDEBAR_SPACE_WIDTH = 350
SIDEBAR_SPACE_HEIGHT = 0
SCREEN_WIDTH, SCREEN_HEIGHT = TILE_WIDTH * VIEW_WIDTH + SIDEBAR_SPACE_WIDTH, TILE_HEIGHT * VIEW_HEIGHT + SIDEBAR_SPACE_HEIGHT  # Extra space for sidebar
ascii_offset_x = TILE_WIDTH//4
ascii_offset_y = TILE_HEIGHT//4

class EditState(Enum):
    TILE = 0
    OBJECT = 1
    INPUT = 2
    
